config/routes.rb
StockAndShares::Application.routes.draw do

	root :to => 'sessions#new'
  
  match '/signup', to: "users#new"
  
  match '/users', to: "users#index"

  match '/home', to: "static_pages#home"

  match '/help', to: "static_pages#help"
  
  match '/about', to: "static_pages#about"

  resources :users
  
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]

  match '/signin', to: "sessions#new"
  
  match '/signout', to: "sessions#destroy"
  

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  attr_accessible :content, :user_id
  
  validates :content, presence: true, length: {maximum: 140}
  validates :user_id, presence: true
  
  default_scope order: 'microposts.created_at DESC'
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime        not null
#  updated_at :datetime        not null
#

class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation
  has_secure_password
  has_many :microposts, dependent: :destroy
  
  before_save {|user| user.email = email.downcase}
  before_save :create_remember_token
  
  validates :name, presence: true, length: {maximum: 50}
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	
  validates :email, presence: true, format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
  
  validates :password, presence: true, length: {minimum: 6}
  
  validate :password_confirmation, presence: true
  
  
  private 
  
   def create_remember_token
		self.remember_token = SecureRandom.urlsafe_base64
   end
  
 end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
	before_filter :signed_in_user, only[:create, :destroy]
	
	def index
	end
	
	def create
	end
	
	def destroy
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		email = params[:session][:email]
		password = params[:session][:password]
		@user = User.find_by_email(email)
		if @user && @user.authenticate(password)
			sign_in @user
			redirect_to @user
		else
			flash.now[:error] = "Invalid email/password combination"
			render 'new'
		end
	end

	def destroy
		sign_out
		redirect_to signin_path
	end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_filter :signed_in_user, only: [:edit, :update, :index, :destroy]
before_filter :correct_user, only: [:edit, :update]
before_filter :admin_user, only: [:destroy]

  def show
	@user = User.find(params[:id])
	@microposts = @user.microposts.paginate(page: params[:page])
  end
  
  def index
	@users = User.paginate(page: params[:page])
  end
  
  def new
	@user = User.new
  end
  
  def create
	@user = User.new(params[:user])
	if @user.save
		sign_in @user
		redirect_back_or @user
	else
		render "new"
	end
  end
  
  def edit
	@user = User.find(params[:id])
  end
  
  def update
	@user = User.find(params[:id])
	if @user.update_attributes(params[:user])
		sign_in @user
		redirect_back_or @user
	else
		render "edit"
	end
  end
  
  def destroy
	User.find(params[:id]).destroy
	flash[:success] = "User destroyed"
	redirect_to users_path
  end
  
  private
  
  def signed_in_user
	unless signed_in?
		store_location
		redirect_to  signin_path, notice: "Please sign in"
	end
  end
  
  def correct_user
	@user = User.find(params[:id])
	redirect_to(root_path) unless current_user? @user
  end
  
  def admin_user
	redirect_to(root_path) unless current_user.admin?
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in(user)
		cookies[:remember_token] = user.remember_token
		self.current_user = user
	end
	
	def signed_in?
		!current_user.nil?
	end
	
	def current_user=(user)
		@current_user = user
	end
	
	def current_user
		@current_user ||= User.find_by_remember_token(cookies[:remember_token])
	end 
	
	def current_user?(user)
		user == current_user
	end
	
	def signed_in_user
		unless signed_in?
			store_location
			redirect_to  signin_path, notice: "Please sign in"
		end
	end

	def sign_out
		self.current_user = nil
		cookies.delete(:remember_token)
	end
	
	def redirect_back_or(default)
		redirect_to (session[:return_to] || default)
		session.delete(:return_to)
	end
	
	def store_location
		session[:return_to] = request.fullpath
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
<nav>
<ul>
<li><%= link_to "About", about_path %></li>
<li><%= link_to "Contact", '#' %></li>
</ul>
</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container">
				
				<%= link_to "Stocks And Shares", home_path, id: "logo" %>
				<nav>
					<ul class="nav pull-right">
						<li><%= link_to "Home", home_path %></li>
						<li><%= link_to "Help", help_path %></li>
						<% if signed_in? %>
							<%= puts "answer #{signed_in?}"%>
							<li><%= link_to "Users", users_path %></li>
							<li id = "fat-menu" class="dropdown">
								<a href="#" class ="dropdown-toggle" data-toggle="dropdown">
								Account<b class="caret"></b>
								</a>
								<ul class="dropdown-menu"> 
									<li><%= link_to "Profile", current_user %></li>
									<li><%= link_to "Settings", edit_user_path(current_user) %></li>
									<li class="divider"></li>
									<li><%= link_to "Sign out", signout_path, method: 'delete'%></li>
								</ul>
							</li>
						<%else%>
							<li><%= link_to "Sign in", "sessions/new" %></li>
						<%end%>	
					</ul>
				</nav>
			</div>
		</div>
	</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
		<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	  <title><%= yield(:title)%></title>
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	  <%= render 'layouts/shim'%>
</head>
<body>
	<%= render 'layouts/header'%>
	<div class="container">
		<%= yield %>
	</div>
	<%=render 'layouts/footer'%>
	<%= debug(params) if Rails.env.development? %>
</body>


</html>

app/views/microposts/_micropost.html.erb
<li>
	<span class="content"><%= micropost.content%></span>
	<span class="timestamp">
		Posted <%= time_ago_in_words(micropost.created_at) %> ago.
	</span>
</li>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-error">
			The form contains <%= pluralize(@user.errors.count, "error") %>.
		</div>
		<ul>
			<% @user.errors.full_messages.each do |msg| %>
			<li>* <%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/shared/_flash.html.erb
<% unless flash[:notice].blank? %>
  <div class="alert-message info">
    <%= content_tag :div, flash[:notice] %>
  </div>
<% end %>

<% unless flash[:error].blank? %>
  <div class="alert-message error">
    <%= content_tag :div, flash[:error] %>
  </div>
<% end %>

<% unless flash[:alert].blank? %>
  <div class="alert-message warning">
    <%= content_tag :div, flash[:alert] %>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About us")%>

<div class = "center hero-unit">
	<h1><%= yield(:title)%></h1>
	<p></p>
	
	
</div>




app/views/static_pages/help.html.erb
<% provide(:title, "Help")%>

<div class = "center hero-unit">
	<h1><%= yield(:title)%></h1>
	<p></p>
	
	
</div>

app/views/static_pages/home.html.erb
<% provide(:title, "Welcome")%>
<div class = "center hero-unit">
	<h1><%= yield(:title)%></h1>
	<p>Latest on Stocks and shares</p>
	
	<%= link_to "Sign up now", signup_path, class: "btn btn-large btn-primary"%>
	
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<li>
	<%= image_tag("profile.jpg", size: "70x70")%>
	<%= link_to user.name, user%>
	<% if current_user.admin? && !current_user?(user) %>
		| <%= link_to "delete", user, method: :delete, confirm: "You sure?"%>
	<%end%>
</li>

app/views/users/edit.html.erb
<%provide(:title, 'Edit Profile')%>

<div class = "center hero-unit">
	<h1>Update your profile</h1>
	<div class="row">
		<div class="span6 offset3">
			<%= form_for(@user) do |f|%>
				<%= render 'shared/error_messages'%>
				
				<%= f.label :name%>
				<%= f.text_field :name%>
				
				<%= f.label :email%>
				<%= f.text_field :email%>
				
				<%= f.label :password%>
				<%= f.password_field :password%>
				
				<%= f.label :password_confirmation, "Confirmation"%>
				<%= f.password_field :password_confirmation%>
				
				<%= f.submit "Save changes", class: "btn btn-large btn-primary"%>
				
			<%end%>
			<div class = "register">
				<%= image_tag("profile.jpg", size: "100x100")%>
				<a href="#">Change</a>
			</div>
		</div>
	</div>
</div>

app/views/users/index.html.erb
<%provide(:title, "All users")%>

<div class = "center hero-unit">
<h1>All Users</h1>

<%= will_paginate%>
	<ul class="users">
		<%= render @users%>
	</ul>
	
<%= will_paginate%>
</div>

app/views/users/new.html.erb
<%provide(:title, 'Sign up')%>

<div class = "center hero-unit">
	<h1>Sign in details</h1>
	<div class="row">
		<div class="span6 offset3">
			<%= form_for(@user) do |f|%>
				<%= render 'shared/error_messages'%>
				<%= f.label :name%>
				<%= f.text_field :name%>
				
				<%= f.label :email%>
				<%= f.text_field :email%>
				
				<%= f.label :password%>
				<%= f.password_field :password%>
				
				<%= f.label :password_confirmation, "Confirmation"%>
				<%= f.password_field :password_confirmation%>
				
				<%= f.submit "Create my account", class: "btn btn-large btn-primary"%>
				
			<%end%>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<%provide(:title, @user.name)%>

<div class = "center hero-unit">
	<div class = "row">
		<aside class="span4">
			<section>
				<h1>
					<%= image_tag("profile.jpg", size: "160x160")%>
					<%= @user.name%>
				</h1>
			</section>
		</aside>
		<div class="span8">
			<% if @user.microposts.any? %>
				<h3>Microposts (<%= @user.microposts.count%>)<h3>
				<ol class="microposts">
					<%= render @microposts%>
				</ol>
				<%= will_paginate @microposts%>
			<%end%>
		</div>
	</div>
	
</div>